/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  "user-center": () => import("@/views/_builtin/user-center/index.vue"),
  home: () => import("@/views/home/index.vue"),
  "system_admin-log_login-log": () => import("@/views/system/admin-log/login-log/index.vue"),
  "system_admin-log_operation-log": () => import("@/views/system/admin-log/operation-log/index.vue"),
  "system_admin-role": () => import("@/views/system/admin-role/index.vue"),
  "system_admin-user": () => import("@/views/system/admin-user/index.vue"),
  system_setting_base: () => import("@/views/system/setting/base/index.vue"),
};
