/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system',
      icon: 'carbon:cloud-service-management',
      order: 2
    },
    children: [
      {
        name: 'system_admin-log',
        path: '/system/admin-log',
        meta: {
          title: 'system_admin-log',
          i18nKey: 'route.system_admin-log',
          icon: 'mdi:file-document-multiple',
          order: 3
        },
        children: [
          {
            name: 'system_admin-log_login-log',
            path: '/system/admin-log/login-log',
            component: 'view.system_admin-log_login-log',
            meta: {
              title: 'system_admin-log_login-log',
              i18nKey: 'route.system_admin-log_login-log',
              icon: 'mdi:file-document',
              order: 0
            }
          },
          {
            name: 'system_admin-log_operation-log',
            path: '/system/admin-log/operation-log',
            component: 'view.system_admin-log_operation-log',
            meta: {
              title: 'system_admin-log_operation-log',
              i18nKey: 'route.system_admin-log_operation-log',
              icon: 'mdi:file-document',
              order: 1
            }
          }
        ]
      },
      {
        name: 'system_admin-role',
        path: '/system/admin-role',
        component: 'view.system_admin-role',
        meta: {
          title: 'system_admin-role',
          i18nKey: 'route.system_admin-role',
          icon: 'carbon:user-role',
          order: 1
        }
      },
      {
        name: 'system_admin-user',
        path: '/system/admin-user',
        component: 'view.system_admin-user',
        meta: {
          title: 'system_admin-user',
          i18nKey: 'route.system_admin-user',
          icon: 'ic:round-manage-accounts',
          order: 2
        }
      },
      {
        name: 'system_setting',
        path: '/system/setting',
        component: 'view.system_setting',
        meta: {
          title: 'system_setting',
          i18nKey: 'route.system_setting',
          icon: 'carbon:settings',
          order: 0
        }
      }
    ]
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base$view.user-center',
    meta: {
      title: 'user-center',
      i18nKey: 'route.user-center',
      hideInMenu: true
    }
  }
];
